---
apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  containers:
  - name: front-end
    image: binocarlos/front-end:0.2.0
    ports:
    - containerPort: 8079
