apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
  labels:
    app: kube-lego
data:
  # modify the next line to specify your address
  lego.email: your-email-here
  lego.url: https://acme-v01.api.letsencrypt.org/directory
