apiVersion: v1
kind: Pod
metadata:
  name: <name>
  labels:
    app: <name>
    colors: blue
    dev: badass
spec:
  containers:
    - name: web
      image: <imgurl>
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP
  env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
