apiVersion: v1
kind: Namespace
metadata:
  name: jujhar

---
apiVersion: v1
kind: Service
metadata:
  name: api-sikhnet-com
  namespace: $N_NAMESPACE
  labels:
    environment: $N_ENVIRONMENT
spec:
  type: NodePort
  ports:
    - port: 80
      name: "http"
      targetPort: 80
  selector:
    app: api-sikhnet-com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: potato-deployment
  namespace: jujhar
  labels:
    app: potato
spec:
  selector:
    matchLabels:
      app: potato
  replicas: 3
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: potato
    spec:
      restartPolicy: Always
      containers:
        - name: web
          image: roubleknew/k8s-training:v2
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: VERSION
              value: "1.1.2.3.2.2.2"
            - name: NODE_ENV
              value: "production"
