---
apiVersion: v1
kind: Pod
metadata:
  name: queue-master
  labels:
    name: queue-master
spec:
  containers:
  - name: queue-master
    image: weaveworksdemos/queue-master:0.3.0
    ports:
    - containerPort: 80
